# Generated by Django 3.1.7 on 2021-03-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
